### ISSUE TITLE
Establish a list of running services

### ISSUE THREAD

**Issue by clee231** [acm-uic/IaC#1]
Create a detailed list of services that are being run by the ACM/LUG servers.  This list should include both public and private services.  Each service should have listings of the following:

* Name of service
* Service Audience (Public: Student, Staff, Faculty, SysAdmins, Alumni, etc.; Private: SysAdmins, X on systems)
* Currently running on... (Which server(s)?)
* Description / Purpose
* Impact (What other things does this service impact by being down/unavailable?)
* Data Locations
* Data Backup Situation
* Running dependencies (What needs to be up before this service can be brought up?)

More to come later?

Still figuring out how exactly we should organize this, but either a WIki article here on GitHub or a markdown document within the repo is fine for now.

**Comment by bmiddha** [comment]
Started wiki page

**Comment by clee231** [comment]
Finished by @avenmia . Thanks!
